import test from "node:test";
import assert from "node:assert/strict";
import { loadConfig, PILES } from "../config.js";
import { BASE_VALUES, RANGES } from "../ranges.js";
import { buildCycle, evolveValues } from "../generator.js";
import { calculateShift, nextSlotFromBase, createSessionId } from "../timelineManager.js";
import { assertDemoClient, assertTransition } from "../validation.js";
import { deduplicate } from "../duplicateGuard.js";
import { MemoryRepository } from "../stateRepository.js";
import { DemoGeneratorService } from "../index.js";
import { hasCompleteReturnPoint } from "../restorationService.js";
import { generatorActivity, isHeartbeatFresh } from "../activity.js";
import { Scheduler } from "../scheduler.js";

const now = new Date("2026-07-22T09:00:00"), config = loadConfig({ DEMO_GENERATOR_ENABLED: "false" });
const cycle = () => buildCycle({ previousByPile: BASE_VALUES, processTime: now, random: () => .75 });
test("genera tres registros por ciclo", () => assert.equal(cycle().length, 3));
test("genera una fila por pila", () => assert.deepEqual(cycle().map(r => r.subarea), PILES));
test("mantiene rangos", () => cycle().forEach(r => Object.entries(RANGES).forEach(([k, v]) => assert.ok(r[k] >= v.min && r[k] <= v.max))));
test("respeta variación máxima", () => { const n = evolveValues(BASE_VALUES["Pila 1"], { random: () => 1 }); Object.entries(RANGES).forEach(([k, v]) => assert.ok(Math.abs(n[k] - BASE_VALUES["Pila 1"][k]) <= v.delta + .001)); });
test("fija cliente demo", () => cycle().forEach(r => assert.equal(r.clienteId, "demo_lixiviacion")));
test("rechaza otro cliente", () => assert.throws(() => assertDemoClient("real")));
test("calcula turnos C A B", () => { assert.equal(calculateShift(new Date("2026-01-01T02:00")), "C"); assert.equal(calculateShift(new Date("2026-01-01T10:00")), "A"); assert.equal(calculateShift(new Date("2026-01-01T18:00")), "B"); });
test("previene duplicados", () => assert.equal(deduplicate([...cycle(), ...cycle()]).length, 3));
test("punto retorno solo normal", () => { const p = Object.fromEntries(cycle().map(r => [r.subarea, r])); assert.ok(hasCompleteReturnPoint(p)); p["Pila 1"].tipoRegistro = "demo_acelerada"; assert.equal(hasCompleteReturnPoint(p), false); });
test("session id estable", () => assert.equal(createSessionId(now), "demo_20260722_090000"));
test("timestamps real y simulado separados", () => { const r = buildCycle({ previousByPile: BASE_VALUES, processTime: new Date(now.getTime() + 3600000), mode: "acelerado", sessionId: "x" })[0]; assert.equal(r.timestampProceso.getTime(), now.getTime() + 3600000); assert.equal(r.timestampCreacion, undefined); });
test("calcula siguiente bloque real", () => assert.equal(nextSlotFromBase(new Date("2026-07-22T09:00"), new Date("2026-07-22T12:30"), 240).getHours(), 13));
test("generador viene desactivado", () => assert.equal(config.enabled, false));
test("identificadores reales", () => { const r = cycle()[0]; assert.equal(r.implementationId, "demo_lixiviacion"); assert.equal(r.profileId, "lixiviacion"); });
test("visible operacional por defecto", () => assert.ok(cycle().every(r => r.visibleOperacional)));
test("transiciones válidas", () => assert.doesNotThrow(() => assertTransition("NORMAL_RUNNING", "DEMO_STARTING")));
test("rechaza transición inválida", () => assert.throws(() => assertTransition("STOPPED", "DEMO_RUNNING")));
test("normal-start usa NORMAL_RUNNING", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); const state = await s.startNormal(); assert.equal(state.estado, "NORMAL_RUNNING"); assert.equal(state.schedulerActive, true); assert.equal(state.processMode, "continuous"); });
test("normal-once termina STOPPED y conserva el ciclo", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await s.normalOnce(); const state = await repo.getState(); assert.equal(repo.records.length, 3); assert.equal(state.estado, "STOPPED"); assert.equal(state.schedulerActive, false); assert.equal(state.processMode, null); assert.equal(state.ultimoResultado.registrosCreados, 3); assert.deepEqual(Object.keys(state.ultimoRegistroAutomaticoNormalPorPila), PILES); });
test("normal continuo conserva NORMAL_RUNNING", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await s.startNormal(); await s.normalOnce({ continuous: true }); const state = await repo.getState(); assert.equal(state.estado, "NORMAL_RUNNING"); assert.equal(state.schedulerActive, true); });
test("detener scheduler vuelve a STOPPED", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now), scheduler = new Scheduler(); scheduler.start(() => Promise.resolve(), 1000); await s.startNormal(); scheduler.stop(); const stopped = await s.stopNormal(); assert.equal(scheduler.running, false); assert.equal(stopped.estado, "STOPPED"); });
test("heartbeat vigente indica proceso activo", () => { const state = { estado: "NORMAL_RUNNING", schedulerActive: true, lastHeartbeatAt: new Date(now.getTime() - 30000) }; assert.equal(isHeartbeatFresh(state, now, 90), true); assert.equal(generatorActivity(state, now, 90).active, true); });
test("heartbeat vencido no se considera activo", () => { const state = { estado: "NORMAL_RUNNING", schedulerActive: true, lastHeartbeatAt: new Date(now.getTime() - 120000) }; const activity = generatorActivity(state, now, 90); assert.equal(activity.active, false); assert.equal(activity.inconsistent, true); });
test("reconcile-state no genera ni modifica históricos", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await s.normalOnce(); const before = structuredClone(repo.records); await repo.saveState({ ...await repo.getState(), estado: "NORMAL_RUNNING" }); const reconciled = await s.reconcileState(); assert.equal(reconciled.estado, "STOPPED"); assert.equal(reconciled.schedulerActive, false); assert.deepEqual(repo.records, before); });
test("reconcile-state rechaza demo activa o restauración", async () => { for (const estado of ["DEMO_RUNNING", "RESTORING_NORMAL"]) { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await repo.saveState({ estado, sessionId: "demo_x" }); await assert.rejects(() => s.reconcileState()); } });
test("reconcile-state rechaza scheduler local", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await assert.rejects(() => s.reconcileState({ localSchedulerActive: true })); });
test("crea demo con punto de retorno", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await s.normalOnce(); const d = await s.startDemo({ scenario: "estable" }); assert.equal(d.estado, "DEMO_RUNNING"); assert.equal(d.sessionId, "demo_20260722_090000"); });
test("rechaza sesiones simultáneas", async () => { const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => now); await s.normalOnce(); await s.startDemo(); await assert.rejects(() => s.startDemo()); });
test("restauración oculta demo e idempotente", async () => { let clock = new Date(now); const repo = new MemoryRepository(), s = new DemoGeneratorService(repo, config, () => clock); await s.normalOnce(); await s.startDemo(); clock = new Date(now.getTime() + 3600000); await s.acceleratedOnce(); const restored = await s.restore(); assert.equal(restored.estado, "STOPPED"); assert.ok(repo.records.filter(r => r.tipoRegistro === "demo_acelerada").every(r => r.visibleOperacional === false)); assert.deepEqual(await s.restore(), restored); });
